import type { CatalogueModel } from './equipment';

// Illustrative examples only: brands are real manufacturers, model labels are
// generic descriptions rather than real model numbers. Catalogue content is
// French because it is displayed as-is.
export const CATALOGUE_MODELS: readonly CatalogueModel[] = [
  {
    id: 'laptop-office-14',
    type: 'laptop',
    brand: 'Dell',
    modelLabel: 'Portable bureautique 14 pouces',
    typicalUse: 'Travail de bureau quotidien : messagerie, suite bureautique, visioconférence.',
    warrantyMonths: 36,
    icon: 'laptop',
  },
  {
    id: 'laptop-ultralight-13',
    type: 'laptop',
    brand: 'Lenovo',
    modelLabel: 'Portable ultraléger 13 pouces',
    typicalUse: 'Poste nomade pour les déplacements fréquents et le télétravail.',
    warrantyMonths: 36,
    icon: 'laptop',
  },
  {
    id: 'laptop-performance-16',
    type: 'laptop',
    brand: 'HP',
    modelLabel: 'Portable performance 16 pouces',
    typicalUse: 'Usages exigeants : tableurs volumineux, virtualisation, traitement d’images.',
    warrantyMonths: 48,
    icon: 'laptop',
  },
  {
    id: 'laptop-creative-14',
    type: 'laptop',
    brand: 'Apple',
    modelLabel: 'Portable création 14 pouces',
    typicalUse: 'Montage, graphisme et développement mobile.',
    warrantyMonths: 24,
    icon: 'laptop',
  },
  {
    id: 'desktop-mini-office',
    type: 'desktop',
    brand: 'HP',
    modelLabel: 'Mini PC bureautique',
    typicalUse: 'Poste fixe compact pour l’accueil, la caisse ou les bureaux partagés.',
    warrantyMonths: 36,
    icon: 'desktop',
  },
  {
    id: 'desktop-tower-workstation',
    type: 'desktop',
    brand: 'Dell',
    modelLabel: 'Tour station de travail',
    typicalUse: 'Poste puissant pour la conception, la comptabilité lourde ou la vidéo.',
    warrantyMonths: 36,
    icon: 'desktop',
  },
  {
    id: 'desktop-all-in-one-24',
    type: 'desktop',
    brand: 'Lenovo',
    modelLabel: 'Tout-en-un 24 pouces',
    typicalUse: 'Poste fixe sans câblage encombrant pour les espaces d’accueil.',
    warrantyMonths: 36,
    icon: 'desktop',
  },
  {
    id: 'printer-laser-mono',
    type: 'printer',
    brand: 'Brother',
    modelLabel: 'Laser monochrome réseau',
    typicalUse: 'Impression de documents texte en volume pour une équipe.',
    warrantyMonths: 24,
    icon: 'printer',
  },
  {
    id: 'printer-laser-colour-mfp',
    type: 'printer',
    brand: 'Canon',
    modelLabel: 'Multifonction laser couleur',
    typicalUse: 'Impression, copie et numérisation couleur pour un service.',
    warrantyMonths: 24,
    icon: 'printer',
  },
  {
    id: 'printer-inkjet-mfp',
    type: 'printer',
    brand: 'Epson',
    modelLabel: 'Multifonction jet d’encre',
    typicalUse: 'Faible volume, impressions couleur occasionnelles.',
    warrantyMonths: 12,
    icon: 'printer',
  },
  {
    id: 'receipt-thermal-80',
    type: 'receipt-printer',
    brand: 'Epson',
    modelLabel: 'Imprimante de tickets thermique 80 mm',
    typicalUse: 'Tickets de caisse et bons de commande en point de vente.',
    warrantyMonths: 24,
    icon: 'receipt-printer',
  },
  {
    id: 'receipt-thermal-58-compact',
    type: 'receipt-printer',
    brand: 'Star Micronics',
    modelLabel: 'Imprimante de tickets compacte 58 mm',
    typicalUse: 'Comptoir à faible encombrement ou terminal mobile.',
    warrantyMonths: 24,
    icon: 'receipt-printer',
  },
  {
    id: 'receipt-thermal-80-network',
    type: 'receipt-printer',
    brand: 'Bixolon',
    modelLabel: 'Imprimante de tickets réseau 80 mm',
    typicalUse: 'Tickets en cuisine ou en réserve, partagée par plusieurs postes.',
    warrantyMonths: 24,
    icon: 'receipt-printer',
  },
  {
    id: 'phone-android-midrange',
    type: 'smartphone',
    brand: 'Samsung',
    modelLabel: 'Smartphone Android milieu de gamme',
    typicalUse: 'Téléphone professionnel standard : appels, messagerie, application métier.',
    warrantyMonths: 24,
    icon: 'smartphone',
  },
  {
    id: 'phone-android-rugged',
    type: 'smartphone',
    brand: 'Samsung',
    modelLabel: 'Smartphone Android renforcé',
    typicalUse: 'Usage en entrepôt ou sur le terrain : chocs, poussière, éclaboussures.',
    warrantyMonths: 24,
    icon: 'smartphone',
  },
  {
    id: 'phone-ios-business',
    type: 'smartphone',
    brand: 'Apple',
    modelLabel: 'Smartphone iOS professionnel',
    typicalUse: 'Téléphone d’encadrement avec gestion centralisée des appareils.',
    warrantyMonths: 12,
    icon: 'smartphone',
  },
  {
    id: 'network-switch-24-poe',
    type: 'network-device',
    brand: 'Cisco',
    modelLabel: 'Commutateur géré 24 ports PoE',
    typicalUse:
      'Cœur de réseau d’un site : relie postes, téléphones et bornes Wi-Fi. Le PoE alimente aussi ces appareils par le câble réseau.',
    warrantyMonths: 60,
    icon: 'network-device',
  },
  {
    id: 'network-access-point-ceiling',
    type: 'network-device',
    brand: 'Ubiquiti',
    modelLabel: 'Borne Wi-Fi plafonnier',
    typicalUse: 'Couverture Wi-Fi des bureaux et des salles de réunion.',
    warrantyMonths: 24,
    icon: 'network-device',
  },
  {
    id: 'network-router-vpn',
    type: 'network-device',
    brand: 'TP-Link',
    modelLabel: 'Routeur VPN petite structure',
    typicalUse:
      'Accès internet et liaison sécurisée avec les autres sites (VPN, réseau privé virtuel) pour un petit site.',
    warrantyMonths: 36,
    icon: 'network-device',
  },
  {
    id: 'network-switch-8-unmanaged',
    type: 'network-device',
    brand: 'Netgear',
    modelLabel: 'Commutateur non géré 8 ports',
    typicalUse: 'Extension de ports sur un bureau ou dans une armoire.',
    warrantyMonths: 36,
    icon: 'network-device',
  },
];

const MODELS_BY_ID: ReadonlyMap<string, CatalogueModel> = new Map(
  CATALOGUE_MODELS.map((model) => [model.id, model]),
);

export function getCatalogueModel(id: string): CatalogueModel | undefined {
  return MODELS_BY_ID.get(id);
}
